test_collatz (test_homework1_79199501.TestExercise1) ... ok
test_collatz_step (test_homework1_79199501.TestExercise1) ... ok
test_collatz_step_error (test_homework1_79199501.TestExercise1) ... ok
test_collatz_step_one (test_homework1_79199501.TestExercise1) ... ok
test_gradient_descent (test_homework1_79199501.TestExercise2) ... ok
test_gradient_descent_nearmin_smallsig (test_homework1_79199501.TestExercise2) ... ok
test_gradient_descent_robust (test_homework1_79199501.TestExercise2) ... ok
test_gradient_step (test_homework1_79199501.TestExercise2) ... ok
test_sigma_condition (test_homework1_79199501.TestExercise2) ... ok
test_decompose (test_homework1_79199501.TestExercise3) ... ok
test_gauss_seidel_iteration (test_homework1_79199501.TestExercise3) ... FAIL
test_gauss_seidel_step (test_homework1_79199501.TestExercise3) ... ok
test_isSDD (test_homework1_79199501.TestExercise3) ... ok
test_jacobi_iteration (test_homework1_79199501.TestExercise3) ... ok
test_jacobi_step (test_homework1_79199501.TestExercise3) ... ok

======================================================================
FAIL: test_gauss_seidel_iteration (test_homework1_79199501.TestExercise3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/santos/Documents/homework1/peterm28/homework1/test_homework1_79199501.py", line 415, in test_gauss_seidel_iteration
    self.assertTrue(round(err-true_err,12)==0)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 15 tests in 0.002s

FAILED (failures=1)
